/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRadiologyRouteImport } from './routes/_app.radiology'
import { Route as AppPrescriptionsRouteImport } from './routes/_app.prescriptions'
import { Route as AppPharmacyRouteImport } from './routes/_app.pharmacy'
import { Route as AppPatientsRouteImport } from './routes/_app.patients'
import { Route as AppOpdRouteImport } from './routes/_app.opd'
import { Route as AppLabRouteImport } from './routes/_app.lab'
import { Route as AppHospitalRouteImport } from './routes/_app.hospital'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppBedsRouteImport } from './routes/_app.beds'
import { Route as AppAppointmentsRouteImport } from './routes/_app.appointments'
import { Route as AppAdminRouteImport } from './routes/_app.admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRadiologyRoute = AppRadiologyRouteImport.update({
  id: '/radiology',
  path: '/radiology',
  getParentRoute: () => AppRoute,
} as any)
const AppPrescriptionsRoute = AppPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppPharmacyRoute = AppPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppOpdRoute = AppOpdRouteImport.update({
  id: '/opd',
  path: '/opd',
  getParentRoute: () => AppRoute,
} as any)
const AppLabRoute = AppLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AppRoute,
} as any)
const AppHospitalRoute = AppHospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppBedsRoute = AppBedsRouteImport.update({
  id: '/beds',
  path: '/beds',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/appointments': typeof AppAppointmentsRoute
  '/beds': typeof AppBedsRoute
  '/billing': typeof AppBillingRoute
  '/hospital': typeof AppHospitalRoute
  '/lab': typeof AppLabRoute
  '/opd': typeof AppOpdRoute
  '/patients': typeof AppPatientsRoute
  '/pharmacy': typeof AppPharmacyRoute
  '/prescriptions': typeof AppPrescriptionsRoute
  '/radiology': typeof AppRadiologyRoute
  '/reports': typeof AppReportsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/appointments': typeof AppAppointmentsRoute
  '/beds': typeof AppBedsRoute
  '/billing': typeof AppBillingRoute
  '/hospital': typeof AppHospitalRoute
  '/lab': typeof AppLabRoute
  '/opd': typeof AppOpdRoute
  '/patients': typeof AppPatientsRoute
  '/pharmacy': typeof AppPharmacyRoute
  '/prescriptions': typeof AppPrescriptionsRoute
  '/radiology': typeof AppRadiologyRoute
  '/reports': typeof AppReportsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/appointments': typeof AppAppointmentsRoute
  '/_app/beds': typeof AppBedsRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/hospital': typeof AppHospitalRoute
  '/_app/lab': typeof AppLabRoute
  '/_app/opd': typeof AppOpdRoute
  '/_app/patients': typeof AppPatientsRoute
  '/_app/pharmacy': typeof AppPharmacyRoute
  '/_app/prescriptions': typeof AppPrescriptionsRoute
  '/_app/radiology': typeof AppRadiologyRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/appointments'
    | '/beds'
    | '/billing'
    | '/hospital'
    | '/lab'
    | '/opd'
    | '/patients'
    | '/pharmacy'
    | '/prescriptions'
    | '/radiology'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/appointments'
    | '/beds'
    | '/billing'
    | '/hospital'
    | '/lab'
    | '/opd'
    | '/patients'
    | '/pharmacy'
    | '/prescriptions'
    | '/radiology'
    | '/reports'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/appointments'
    | '/_app/beds'
    | '/_app/billing'
    | '/_app/hospital'
    | '/_app/lab'
    | '/_app/opd'
    | '/_app/patients'
    | '/_app/pharmacy'
    | '/_app/prescriptions'
    | '/_app/radiology'
    | '/_app/reports'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/radiology': {
      id: '/_app/radiology'
      path: '/radiology'
      fullPath: '/radiology'
      preLoaderRoute: typeof AppRadiologyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prescriptions': {
      id: '/_app/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof AppPrescriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pharmacy': {
      id: '/_app/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AppPharmacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opd': {
      id: '/_app/opd'
      path: '/opd'
      fullPath: '/opd'
      preLoaderRoute: typeof AppOpdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lab': {
      id: '/_app/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AppLabRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hospital': {
      id: '/_app/hospital'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof AppHospitalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/beds': {
      id: '/_app/beds'
      path: '/beds'
      fullPath: '/beds'
      preLoaderRoute: typeof AppBedsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppBedsRoute: typeof AppBedsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppHospitalRoute: typeof AppHospitalRoute
  AppLabRoute: typeof AppLabRoute
  AppOpdRoute: typeof AppOpdRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppPharmacyRoute: typeof AppPharmacyRoute
  AppPrescriptionsRoute: typeof AppPrescriptionsRoute
  AppRadiologyRoute: typeof AppRadiologyRoute
  AppReportsRoute: typeof AppReportsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppBedsRoute: AppBedsRoute,
  AppBillingRoute: AppBillingRoute,
  AppHospitalRoute: AppHospitalRoute,
  AppLabRoute: AppLabRoute,
  AppOpdRoute: AppOpdRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppPharmacyRoute: AppPharmacyRoute,
  AppPrescriptionsRoute: AppPrescriptionsRoute,
  AppRadiologyRoute: AppRadiologyRoute,
  AppReportsRoute: AppReportsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
